version: '3.9'

services:

  chromadb:
      build:
        context: ./chromadb
        dockerfile: Dockerfile
      image: ${CHROMADB_IMAGE}
      volumes:
        - ./chroma:/chroma/chroma
      environment:
        - IS_PERSISTENT=TRUE
        - ANONYMIZED_TELEMETRY=TRUE 
        - http_proxy=${http_proxy}
        - https_proxy=${http_proxy}
        - no_proxy=${no_proxy}
      ports:
        - 8000:8000
      healthcheck:
        test: curl --fail http://localhost:8000/api/v1/heartbeat || exit 1
        interval: 30s
        retries: 10
        start_period: 60s
        timeout: 5s

  ca-chatbot-rag:
      build:
        context: ./rag
        dockerfile: Dockerfile
      image: ${CHATBOT_RAG_IMAGE}
      environment:
        - CHROMA_HOST=chromadb
        - INDEX_COLLECTION_NAME=adrs
        - STREAMLIT_SERVER_ENABLE_STATIC_SERVING=true
        - CHROMA_PORT=8000
        - OPENAI_API_KEY=${OPENAI_API_KEY_RAG}
        - BASE_URL=${BASE_URL}
        - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN_RAG}
        - IS_OPEN_SOURCE=${IS_OPEN_SOURCE}
        - NUMBER_OF_RESULTS=${NUMBER_OF_RESULTS}                
        - MARKDOWN_IN_HTML=${MARKDOWN_IN_HTML}
        - http_proxy=${http_proxy}
        - https_proxy=${http_proxy}
        - no_proxy=${no_proxy}
      volumes:
        - ./adrs:/app/static/adrs
      ports:  
        - 9090:9090
      depends_on:
        chromadb:
           condition: service_healthy
        
  ca-chatbot-indexing:
      build:
        context: ./indexing
        dockerfile: Dockerfile
      image: ${CHATBOT_INDEXING_IMAGE}
      environment:
        - CHROMA_HOST=chromadb
        - INDEX_COLLECTION_NAME=adrs
        - CHROMA_PORT=8000
        - OPENAI_API_KEY=${OPENAI_API_KEY_INDEXING}
        - ADRS_PATH=/adrs
        - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN_INDEXING}
        - IS_OPEN_SOURCE=${IS_OPEN_SOURCE}
        - FILE_TYPE=${FILE_TYPE}
        - http_proxy=${http_proxy}
        - https_proxy=${http_proxy}
        - no_proxy=${no_proxy}
      volumes:
        - ./adrs:/adrs
      depends_on:
        chromadb:
           condition: service_healthy

volumes:
  chroma:
    driver: local
  adrs:
    driver: local
